### ISSUE TITLE
未找到到Model对象

### ISSUE THREAD

**Issue by xuanxuan26** [284772894/auto_http_api#1]
class email(Model):
    to_addr = ListType(StringType)
    mail_host = StringType()
    mail_user = StringType()
    mail_pass = StringType()
    port = IntType()
    headerMsg = StringType()
    attach = StringType()
    report = StringType()
    file = StringType()

最近在看大牛的自动化源代码，但在看源代码时，Model对象未找到，想问下此Model文件是未上传还是什么情况，望大牛赐教

**Comment by xuanxuan26** [comment]
如果是忘记上传，能否给我一份呢，非常感谢

**Comment by Louis-me** [comment]
用pip 安装缺少模块，pip install schematics
